### ISSUE TITLE
Please rename your package

### ISSUE THREAD

**Issue by wdavidw** [everettcaleb/node-csv-parse#4]
Hi, I'm the author of the "csv-parse" module. Would you be kind enough to rename your package. I am for multiple csv parser in the Node.js land but the name you choose is [really confusing for users](https://github.com/wdavidw/node-csv-parse/issues/115) when  "csv-parse" has existed for years.
Thank you for your understanding

**Comment by everettcaleb** [comment]
Pretty sure I can't rename a public NPM package because of their policies. Sorry for the inconvenience.

**Comment by wdavidw** [comment]
Yes, i'm aware of their policy. `npm deprecate` followed with the publication of a new package would do just fine. Thanks for taking my request into consideration.

**Comment by everettcaleb** [comment]
I'll look into that right now.

**Comment by everettcaleb** [comment]
It should be deprecated now. Thanks for bringing this to my attention.
![screen shot 2017-01-27 at 1 27 05 pm](https://cloud.githubusercontent.com/assets/6482053/22382620/6c442262-e494-11e6-9fcb-dd7a8b768bcf.png)

**Comment by wdavidw** [comment]
Great, I'm really grateful for your understanding
